title: Arjun Rao
description: Graduating from Ramaiah Institute of Technology with a BE in Information Science and Engineering.
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-116323344-1
